export const REQUEST_POSTS = 'REQUEST_POSTS'

export const AUTHENTICATED_SUCCESS = 'AUTHENTICATED_SUCCESS'

export const FETCH_LOGIN = 'FETCH_LOGIN'
export const FETCH_LOGIN_SUCCESS = 'FETCH_LOGIN_SUCCESS'
export const FETCH_LOGIN_ERROR = 'FETCH_LOGIN_ERROR'

export const TOKEN_LOGIN = 'TOKEN_LOGIN'
export const TOKEN_LOGIN_SUCCESS = 'TOKEN_LOGIN_SUCCESS'
export const TOKEN_LOGIN_ERROR = 'TOKEN_LOGIN_ERROR'

export const UPLOAD_PICTURE = 'UPLOAD_PICTURE'
export const UPLOAD_PICTURE_SUCCESS = 'UPLOAD_PICTURE_SUCCESS'
export const UPLOAD_PICTURE_ERROR = 'UPLOAD_PICTURE_ERROR'
