export const REQUEST_POSTS = 'REQUEST_POSTS'

export const AUTHENTICATED_SUCCESS = 'AUTHENTICATED_SUCCESS'

export const FETCH_LOGIN = 'FETCH_LOGIN'
export const FETCH_LOGIN_SUCCESS = 'FETCH_LOGIN_SUCCESS'
export const FETCH_LOGIN_ERROR = 'FETCH_LOGIN_ERROR'
